### ISSUE TITLE
landscape with four items flickers

### ISSUE THREAD

**Issue by basseur** [bonndan/nivio#34]
Reloading the graph.png renders different every time for 4 groups.

```
identifier: AdventOfCode
name: Advent Of Code App
contact: basseur@mail.de


# Landscape configuration
config:
  groups:
    input:
      color: "0c8e3e"
    Frontend:
      color: "24a0ed"

  # https://jgraph.github.io/mxgraph/java/docs/com/mxgraph/layout/mxOrganicLayout.html
  jgraphx:
 #   triesPerCell: 8
 #   edgeLengthCostFactor: 0.0001
    nodeDistributionCostFactor: 900000.0
 #   borderLineCostFactor: 7.0

    #
    # for group alignment
    #

    # the higher, the longer the edges between groups
    forceConstantFactor: 4.0

    # higher value is cpu intensive, but can lead to better layouts
   # maxIterations: 1000

items:

  - identifier: user
    name: User
    type: humanuser
    group: input
    dataFlow:
      - target: fe-react
        description: User inputs data into React Frontend

  - identifier: fe-react
    name: React
    group: Frontend
    dataflow:
      - target: be-controller
        description: Using a REST-API, the data is sent to the backend

  - identifier: be-controller
    name: Controller
    group: Backend
    dataflow:
      - target: be-services
        description: Sends puzzle input to services
      - target: fe-react
        description: Sends puzzle output to frontent

  - identifier: be-services
    name: Services
    group: Backend
    dataflow:
      - target: be-persistence
        description: Sends puzzle results to the persistence layer
      - target: be-controller
        description: Sends puzzle results to the controller


  - identifier: be-persistence
    name: Persistence
    group: Backend
    dataflow:
      - target: postgres
        description: Data is stored in a PostgreSQL DB
      - target: be-service
        description: Returns retrieved data

  - identifier: postgres
    name: PostgreSQL DB
    group: Persistence
    type: database
    lifecycle: planned
```
